### ISSUE TITLE
Lint issues on master

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2249]
## Expected Behavior 

`make lint-python` should work on master

## Current Behavior

`make lint-python` yields the following error:

```
feast/feature_store.py:1440: error: Name 'FieldStatus.ValueType' is not defined
feast/feature_store.py:1493: error: Name 'FieldStatus.ValueType' is not defined
```

I suspect this issue was introduced by #2223, and is occurring due to some packages being out of date (most likely `mypy-protobuf` or something related). In particular, this kind of typing is described [here](https://openbase.com/python/mypy-protobuf/documentation#types-enum-int-values-more-strongly), so it should be correct.

A probably related issue is that `CI_REQUIRED` contains `mypy-protobuf==3.1.0` but `DEV_REQUIRED` contains `mypy-protobuf==1.*`.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by judahrand** [comment]
That dev requirement does look like the issue! Apologies for that an oversight on my behalf. So many places to update dependencies!
